export enum Environments {
  NODE_ENV = "NODE_ENV",
  AUTH_MICROSERVICE_PORT = "AUTH_MICROSERVICE_PORT",
  LOG_LEVEL = "LOG_LEVEL",
  ACCESS_TOKEN_EXPIRATION = "ACCESS_TOKEN_EXPIRATION",
  REFRESH_TOKEN_EXPIRATION = "REFRESH_TOKEN_EXPIRATION",
}
